baseURL: "https://notes.andreasalvatori.dev"
title: Andrea Salvatori's notes
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    disabled: false
    languageCode: en-US
    weight: 2
    taxonomies:
      category: categories
      tag: tags
      search: search
    menu:
      main:
        - name: search
          url: search
          weight: 10
        - identifier: categories
          name: categories
          url: categories/
          weight: 10
        - identifier: tags
          name: tags
          url: tags/
          weight: 10
  it:
    languageName: "Italian"
    disabled: false
    languageCode: it-IT
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: search
          url: search
          weight: 10
        - identifier: categories
          name: categories
          url: categories/
          weight: 10
        - identifier: tags
          name: tags
          url: tags/
          weight: 10

defaultContentLanguage: "it"
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: Andrea Salvatori's notes
  description: "Notes from after-work works"
  keywords: [Blog, Notes, PaperMod]
  author: [Andrea Salvatori]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  social: true # Workaround waiting for PR #1620

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple_touch_icon.png"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple_touch_icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F984"
    Content: >-
      That is my personal "block notes" about hobbies.
      Social links in the [personal site](https://andreasalvatori.dev).
  
  # socialIcons: # optional
  #   - name: other
  #     title: website
  #     url: "https://andreasalvatori.dev"

  ShareButtons: ["whatsapp", "telegram", "twitter"]

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/Sonic0/notes.andreasalvatori.dev/edit/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    lineNos: true
    style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON

deployment:
  targets:
    - name: "AWS-S3"
      URL: "s3://<Bucket Name>?region=<AWS region>"
      exclude: "media/images/*"
      cloudFrontDistributionID: <Distribution ID>
