name: Deploy site to S3

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to deploy'
        default: 'main'
        required: false
        type: string
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.127.0"
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
  release:
    types: [ released ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Deploy to S3
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.127.0' }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release || 'main' }}

      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/public'
          key: ${{ runner.os }}-hugo-${{ hashFiles('public/index.html') }}

      - name: Install AWS CLI v2
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Get Hugo Theme
        run: git submodule update --init --recursive

      - name: Build
        run: hugo --gc -DEF --baseURL "https://${{ env.URL }}"
        env:
          URL: notes.andreasalvatori.dev

  deploy:
    environment:
      name: AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Assume AWS IAM Role
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Config file target substitutions
        run: 

      - name: Deploy to S3
        run: hugo deploy --maxDeletes -1 --invalidateCDN --target ${{ secrets.BUCKET_NAME }} --logLevel info
